<a href="https://colab.research.google.com/github/DaniliukK95/Drops_Of_Jupyter/blob/Amy-Ying-Lin/cleaned2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, confusion_matrix

In [5]:
%matplotlib notebook

In [6]:
# change your file path to load it
clean_df2 = pd.read_csv('clean.csv')
clean_df2.head()

Unnamed: 0 Unique ID  Household region  Age of sample adult  \
0           0   H056808                 3                   50   
1           1   H018779                 3                   53   
2           2   H049265                 3                   56   
3           3   H007699                 3                   57   
4           4   H066034                 3                   25   

   Sex of sample adult  Education of sample adult  Hispanic ethnicity of SA  \
0                    1                          1                         2   
1                    1                          7                         2   
2                    1                          8                         2   
3                    2                          5                         2   
4                    1                          4                         2   

   Single + Mult race gps w Hispanic origin  Hispanic origin detail  \
0                                         2                       3   
1                                         3                       3   
2                                         2                       3   
3                                         2                       3   
4                                         3                       3   

   Single and multiple race groups  ...  Medicaid HDHP.1  \
0                                1  ...              NaN   
1                                2  ...              NaN   
2                                1  ...              NaN   
3                                1  ...              NaN   
4                                2  ...              NaN   

   Medicaid reassignment flag  Paid for by Medicare - plan 1  \
0                         NaN                            2.0   
1                         NaN                            2.0   
2                         NaN                            2.0   
3                         NaN                            NaN   
4                         NaN                            2.0   

   Paid for by Medicare - plan 2  \
0                            NaN   
1                            NaN   
2                            NaN   
3                            NaN   
4                            NaN   

   Not eligible for Medicaid, CHIP, or other public coverage  \
0                                                NaN           
1                                                NaN           
2                                                NaN           
3                                                NaN           
4                                                NaN           

   SA family poverty ratio  \
0                     1.93   
1                     4.45   
2                     5.94   
3                     3.70   
4                     1.66   

   Ratio of family income to poverty threshold for SA’s family  \
0                                                  7             
1                                                 12             
2                                                 14             
3                                                 11             
4                                                  6             

   income from wages  income from SSI SSDI  income from retirement  
0                  1                   2.0                     2.0  
1                  1                   2.0                     2.0  
2                  1                   2.0                     2.0  
3                  1                   1.0                     1.0  
4                  8                   NaN                     NaN  

[5 rows x 40 columns]

## correlation bet. taking diab. pill and income from wates

In [7]:
# taking diab. pill & income from wages cols
clean_df3 = clean_df2.loc[:, ['Taking diabetic pills', 'income from wages'] ]
clean_df3

Taking diabetic pills  income from wages
0                        1.0                  1
1                        1.0                  1
2                        NaN                  1
3                        NaN                  1
4                        NaN                  8
...                      ...                ...
29477                    NaN                  2
29478                    1.0                  1
29479                    NaN                  2
29480                    NaN                  2
29481                    1.0                  1

[29482 rows x 2 columns]

In [9]:
# .dropna()
clean_df4 = clean_df3.dropna()
clean_df4

Taking diabetic pills  income from wages
0                        1.0                  1
1                        1.0                  1
8                        2.0                  1
12                       1.0                  8
15                       2.0                  1
...                      ...                ...
29470                    1.0                  2
29473                    1.0                  2
29476                    1.0                  1
29478                    1.0                  1
29481                    1.0                  1

[5702 rows x 2 columns]

### splite the data into training and testing

pandas.get_dummies(data, columns='')

convert categorical variable into dummy/indicator variables

In [10]:
# conver cate. var. into indicators
clean_df5 = pd.get_dummies(clean_df4, columns=['Taking diabetic pills',
                                              'income from wages'])
clean_df5

Taking diabetic pills_1.0  Taking diabetic pills_2.0  \
0                              1                          0   
1                              1                          0   
8                              0                          1   
12                             1                          0   
15                             0                          1   
...                          ...                        ...   
29470                          1                          0   
29473                          1                          0   
29476                          1                          0   
29478                          1                          0   
29481                          1                          0   

       Taking diabetic pills_7.0  Taking diabetic pills_9.0  \
0                              0                          0   
1                              0                          0   
8                              0                          0   
12                             0                          0   
15                             0                          0   
...                          ...                        ...   
29470                          0                          0   
29473                          0                          0   
29476                          0                          0   
29478                          0                          0   
29481                          0                          0   

       income from wages_1  income from wages_2  income from wages_7  \
0                        1                    0                    0   
1                        1                    0                    0   
8                        1                    0                    0   
12                       0                    0                    0   
15                       1                    0                    0   
...                    ...                  ...                  ...   
29470                    0                    1                    0   
29473                    0                    1                    0   
29476                    1                    0                    0   
29478                    1                    0                    0   
29481                    1                    0                    0   

       income from wages_8  income from wages_9  
0                        0                    0  
1                        0                    0  
8                        0                    0  
12                       1                    0  
15                       0                    0  
...                    ...                  ...  
29470                    0                    0  
29473                    0                    0  
29476                    0                    0  
29478                    0                    0  
29481                    0                    0  

[5702 rows x 9 columns]

In [11]:
# drop anything but 'taking diabetic pill_1.0' (target)
clean_df6 = clean_df5.drop(columns={'Taking diabetic pills_2.0', 'Taking diabetic pills_7.0','Taking diabetic pills_9.0'})
clean_df6

Taking diabetic pills_1.0  income from wages_1  income from wages_2  \
0                              1                    1                    0   
1                              1                    1                    0   
8                              0                    1                    0   
12                             1                    0                    0   
15                             0                    1                    0   
...                          ...                  ...                  ...   
29470                          1                    0                    1   
29473                          1                    0                    1   
29476                          1                    1                    0   
29478                          1                    1                    0   
29481                          1                    1                    0   

       income from wages_7  income from wages_8  income from wages_9  
0                        0                    0                    0  
1                        0                    0                    0  
8                        0                    0                    0  
12                       0                    1                    0  
15                       0                    0                    0  
...                    ...                  ...                  ...  
29470                    0                    0                    0  
29473                    0                    0                    0  
29476                    0                    0                    0  
29478                    0                    0                    0  
29481                    0                    0                    0  

[5702 rows x 6 columns]

In [12]:
# create our features
X = clean_df6.drop(columns=['Taking diabetic pills_1.0'])
X.head()

income from wages_1  income from wages_2  income from wages_7  \
0                     1                    0                    0   
1                     1                    0                    0   
8                     1                    0                    0   
12                    0                    0                    0   
15                    1                    0                    0   

    income from wages_8  income from wages_9  
0                     0                    0  
1                     0                    0  
8                     0                    0  
12                    1                    0  
15                    0                    0

In [14]:
# create the target
y = clean_df6['Taking diabetic pills_1.0']
y[:5]

0     1
1     1
8     0
12    1
15    0
Name: Taking diabetic pills_1.0, dtype: uint8

In [15]:
# check the balance of the target value
y.value_counts()

# result: good, 1:1 ratio of taking vs. not taking, no need to resample the data

0    2897
1    2805
Name: Taking diabetic pills_1.0, dtype: int64

### Split the data into train and test set

In [31]:
# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [32]:
# create a scaler instance
import sklearn as skl
X_scaler = skl.preprocessing.StandardScaler()

#from sklearn.preprocessing import StandardScaler

In [33]:
# fit/train the scaler
X_scaler.fit(X_train)

StandardScaler()

In [34]:
# scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [35]:
print (X_train_scaled)

[[ 0.89043367 -0.82311639 -0.07512924 -0.1826183  -0.02163205]
 [ 0.89043367 -0.82311639 -0.07512924 -0.1826183  -0.02163205]
 [ 0.89043367 -0.82311639 -0.07512924 -0.1826183  -0.02163205]
 ...
 [ 0.89043367 -0.82311639 -0.07512924 -0.1826183  -0.02163205]
 [-1.12304828  1.21489501 -0.07512924 -0.1826183  -0.02163205]
 [-1.12304828 -0.82311639 -0.07512924  5.47590241 -0.02163205]]


In [36]:
print(X_test_scaled)

[[ 0.89043367 -0.82311639 -0.07512924 -0.1826183  -0.02163205]
 [-1.12304828  1.21489501 -0.07512924 -0.1826183  -0.02163205]
 [-1.12304828  1.21489501 -0.07512924 -0.1826183  -0.02163205]
 ...
 [ 0.89043367 -0.82311639 -0.07512924 -0.1826183  -0.02163205]
 [ 0.89043367 -0.82311639 -0.07512924 -0.1826183  -0.02163205]
 [-1.12304828  1.21489501 -0.07512924 -0.1826183  -0.02163205]]


In [37]:
# 75% train, 25% test 
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(4276, 5)
(1426, 5)


In [38]:
# 75% train, 25% test 
print(y_train.shape)
print(y_test.shape)

(4276,)
(1426,)


In [39]:
# create a logistic regression model
model = LogisticRegression(solver='lbfgs', random_state=1)
model

#model.fit(X_scaled, y)

LogisticRegression(random_state=1)

In [40]:
# fit (train) model using the training data
model.fit(X_train_scaled, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=1)

### make predictions

In [26]:
# # predict outcomes for the test data set
predictions = model.predict(X_test_scaled)
pd.DataFrame( {'Prediction': predictions, 'Acutal': y_test} )

Prediction  Acutal
28868           0       0
12947           1       1
3527            0       0
16349           0       0
5473            1       1
...           ...     ...
28848           1       0
15034           1       1
25553           1       0
21590           0       1
23840           0       0

[1426 rows x 2 columns]

In [27]:
# cal. the balanced accuracy score
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

# poor correlation between income and diabetes 

0.526889665010576

## looping over 38 cat. variables

In [41]:
import sklearn as skl

target_column = "Taking diabetic pills"

target_column_onehot = '1.0'

for column in clean_df2.columns.values:
    if target_column != column:
        XY = clean_df2[ [column,"Taking diabetic pills"] ].copy()
        XY = XY.dropna()
        X = pd.get_dummies( XY[ column ].astype('str') )
        y = pd.get_dummies( XY[ target_column ].astype('str') ) 
        y = y[ target_column_onehot ]
        print(column,X.shape,y.shape)
        X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
        X_scaler = skl.preprocessing.StandardScaler()
        X_scaler.fit(X_train)
        X_train_scaled = X_scaler.transform(X_train)
        X_test_scaled = X_scaler.transform(X_test)
        model = LogisticRegression(solver='lbfgs', random_state=1)
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        print( column, "score", balanced_accuracy_score(y_test, y_pred) )
    #break

Unnamed: 0 (5702, 5702) (5702,)
Unnamed: 0 score 0.5
Unique ID (5702, 5702) (5702,)
Unique ID score 0.5
Household region (5702, 4) (5702,)
Household region score 0.49483890009346254
Age of sample adult (5702, 70) (5702,)
Age of sample adult score 0.542354272221949
Sex of sample adult (5702, 2) (5702,)
Sex of sample adult score 0.5490953809828324
Education of sample adult (5702, 12) (5702,)
Education of sample adult score 0.5399783560430912
Hispanic ethnicity of SA (5702, 2) (5702,)
Hispanic ethnicity of SA score 0.5180294161050716
Single + Mult race gps w Hispanic origin (5702, 7) (5702,)
Single + Mult race gps w Hispanic origin score 0.5191440798858773
Hispanic origin detail (5702, 5) (5702,)
Hispanic origin detail score 0.5180294161050716
Single and multiple race groups (5702, 8) (5702,)
Single and multiple race groups score 0.5141610507157263
General health status (5702, 6) (5702,)
General health status score 0.5620984800039353
Ever had Diabetes? (5702, 3) (5702,)
Ever had Diabetes?

In [ ]:
import sklearn as skl

target_column = "Taking diabetic pills"

target_column_onehot = '1.0'

for column in clean_df2.columns.values:
    if target_column != column:
        XY = clean_df2[ [column,"Taking diabetic pills"] ].copy()
        XY = XY.dropna()
        if len( XY ) > 0:
            if len( XY[column] ) == len( XY[target_column] ):
                X = pd.get_dummies( XY[ column ].astype('str') )
                y = pd.get_dummies( XY[ target_column ].astype('str') ) 
                y = y[ target_column_onehot ]
                print(column,X.shape,y.shape)
                X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
                X_scaler = skl.preprocessing.StandardScaler()
                X_scaler.fit(X_train)
                X_train_scaled = X_scaler.transform(X_train)
                X_test_scaled = X_scaler.transform(X_test)
                model = LogisticRegression(solver='lbfgs', random_state=1)
                model.fit(X_train, y_train)
                y_pred = model.predict(X_test)
                print( column, "score", balanced_accuracy_score(y_test, y_pred) )
    #break

In [ ]:
clean_df2.columns

In [ ]:
import sklearn as skl

target_column = "Taking diabetic pills"
target_column_onehot = '1.0'

columns=['Age of sample adult',
         'Sex of sample adult',
         'Education of sample adult',
         'Single + Mult race gps w Hispanic origin',
         'income from wages']
XYcolumns = columns+[target_column]
print(XYcolumns)
XY = clean_df2.loc[ :, XYcolumns ].copy()
XY = XY.dropna()
X = pd.get_dummies( XY[ columns ].astype('str') )
y = pd.get_dummies( XY[ target_column ].astype('str') ) 
y = y[ target_column_onehot ]
print(columns,X.shape,y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
X_scaler = skl.preprocessing.StandardScaler()
X_scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print( "Score", balanced_accuracy_score(y_test, y_pred) )
    #break

In [ ]:
([1]+[2])

In [ ]:
# give column title loop thru the 38 col. 
#for column in clean_df2.columns.values:
     #  print(clean_df2.columns.values)

In [ ]:
for col in clean_df2:
    X = pd.get_dummies(clean_df2[col])
    print(X.head(5))

In [ ]:
for col in clean_df2.columns.values:
    X = pd.get_dummies(clean_df2[col])
    print(X.head(5))