<a href="https://colab.research.google.com/github/DaniliukK95/Drops_Of_Jupyter/blob/Amy-Ying-Lin/cleaned2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, confusion_matrix

In [16]:
%matplotlib notebook

In [17]:
# change your file path to load it
clean_df2 = pd.read_csv('clean.csv')
clean_df2.head()

Unnamed: 0 Unique ID  Household region  Age of sample adult  \
0           0   H056808                 3                   50   
1           1   H018779                 3                   53   
2           2   H049265                 3                   56   
3           3   H007699                 3                   57   
4           4   H066034                 3                   25   

   Sex of sample adult  Education of sample adult  Hispanic ethnicity of SA  \
0                    1                          1                         2   
1                    1                          7                         2   
2                    1                          8                         2   
3                    2                          5                         2   
4                    1                          4                         2   

   Single + Mult race gps w Hispanic origin  Hispanic origin detail  \
0                                         2                       3   
1                                         3                       3   
2                                         2                       3   
3                                         2                       3   
4                                         3                       3   

   Single and multiple race groups  ...  Medicaid HDHP.1  \
0                                1  ...              NaN   
1                                2  ...              NaN   
2                                1  ...              NaN   
3                                1  ...              NaN   
4                                2  ...              NaN   

   Medicaid reassignment flag  Paid for by Medicare - plan 1  \
0                         NaN                            2.0   
1                         NaN                            2.0   
2                         NaN                            2.0   
3                         NaN                            NaN   
4                         NaN                            2.0   

   Paid for by Medicare - plan 2  \
0                            NaN   
1                            NaN   
2                            NaN   
3                            NaN   
4                            NaN   

   Not eligible for Medicaid, CHIP, or other public coverage  \
0                                                NaN           
1                                                NaN           
2                                                NaN           
3                                                NaN           
4                                                NaN           

   SA family poverty ratio  \
0                     1.93   
1                     4.45   
2                     5.94   
3                     3.70   
4                     1.66   

   Ratio of family income to poverty threshold for SA’s family  \
0                                                  7             
1                                                 12             
2                                                 14             
3                                                 11             
4                                                  6             

   income from wages  income from SSI SSDI  income from retirement  
0                  1                   2.0                     2.0  
1                  1                   2.0                     2.0  
2                  1                   2.0                     2.0  
3                  1                   1.0                     1.0  
4                  8                   NaN                     NaN  

[5 rows x 40 columns]

## correlation bet. taking diab. pill and income from wates

In [18]:
# taking diab. pill & income from wages cols
clean_df3 = clean_df2.loc[:, ['Taking diabetic pills', 'income from wages'] ]
clean_df3

Taking diabetic pills  income from wages
0                        1.0                  1
1                        1.0                  1
2                        NaN                  1
3                        NaN                  1
4                        NaN                  8
...                      ...                ...
29477                    NaN                  2
29478                    1.0                  1
29479                    NaN                  2
29480                    NaN                  2
29481                    1.0                  1

[29482 rows x 2 columns]

In [19]:
# can't pd.get_dummies and .loc[] together
#clean_df3 = pd.get_dummies(clean_df3.loc[:,['Taking diabetic pills',
  #                                            'income from wages'] ] )
#clean_df3

In [20]:
# .dropna()
clean_df4 = clean_df3.dropna()
clean_df4

Taking diabetic pills  income from wages
0                        1.0                  1
1                        1.0                  1
8                        2.0                  1
12                       1.0                  8
15                       2.0                  1
...                      ...                ...
29470                    1.0                  2
29473                    1.0                  2
29476                    1.0                  1
29478                    1.0                  1
29481                    1.0                  1

[5702 rows x 2 columns]

### splite the data into training and testing

pandas.get_dummies(data, columns='')

convert categorical variable into dummy/indicator variables

In [21]:
# conver cate. var. into indicators
clean_df5 = pd.get_dummies(clean_df4, columns=['Taking diabetic pills',
                                              'income from wages'])
clean_df5

Taking diabetic pills_1.0  Taking diabetic pills_2.0  \
0                              1                          0   
1                              1                          0   
8                              0                          1   
12                             1                          0   
15                             0                          1   
...                          ...                        ...   
29470                          1                          0   
29473                          1                          0   
29476                          1                          0   
29478                          1                          0   
29481                          1                          0   

       Taking diabetic pills_7.0  Taking diabetic pills_9.0  \
0                              0                          0   
1                              0                          0   
8                              0                          0   
12                             0                          0   
15                             0                          0   
...                          ...                        ...   
29470                          0                          0   
29473                          0                          0   
29476                          0                          0   
29478                          0                          0   
29481                          0                          0   

       income from wages_1  income from wages_2  income from wages_7  \
0                        1                    0                    0   
1                        1                    0                    0   
8                        1                    0                    0   
12                       0                    0                    0   
15                       1                    0                    0   
...                    ...                  ...                  ...   
29470                    0                    1                    0   
29473                    0                    1                    0   
29476                    1                    0                    0   
29478                    1                    0                    0   
29481                    1                    0                    0   

       income from wages_8  income from wages_9  
0                        0                    0  
1                        0                    0  
8                        0                    0  
12                       1                    0  
15                       0                    0  
...                    ...                  ...  
29470                    0                    0  
29473                    0                    0  
29476                    0                    0  
29478                    0                    0  
29481                    0                    0  

[5702 rows x 9 columns]

In [22]:
# drop anything but 'taking diabetic pill_1.0' (target)
clean_df6 = clean_df5.drop(columns={'Taking diabetic pills_2.0', 'Taking diabetic pills_7.0','Taking diabetic pills_9.0'})
clean_df6

Taking diabetic pills_1.0  income from wages_1  income from wages_2  \
0                              1                    1                    0   
1                              1                    1                    0   
8                              0                    1                    0   
12                             1                    0                    0   
15                             0                    1                    0   
...                          ...                  ...                  ...   
29470                          1                    0                    1   
29473                          1                    0                    1   
29476                          1                    1                    0   
29478                          1                    1                    0   
29481                          1                    1                    0   

       income from wages_7  income from wages_8  income from wages_9  
0                        0                    0                    0  
1                        0                    0                    0  
8                        0                    0                    0  
12                       0                    1                    0  
15                       0                    0                    0  
...                    ...                  ...                  ...  
29470                    0                    0                    0  
29473                    0                    0                    0  
29476                    0                    0                    0  
29478                    0                    0                    0  
29481                    0                    0                    0  

[5702 rows x 6 columns]

In [23]:
# create our features
X = clean_df6.drop(columns=['Taking diabetic pills_1.0'])
X.head()

income from wages_1  income from wages_2  income from wages_7  \
0                     1                    0                    0   
1                     1                    0                    0   
8                     1                    0                    0   
12                    0                    0                    0   
15                    1                    0                    0   

    income from wages_8  income from wages_9  
0                     0                    0  
1                     0                    0  
8                     0                    0  
12                    1                    0  
15                    0                    0

In [24]:
# stats of X 
X.describe()

income from wages_1  income from wages_2  income from wages_7  \
count          5702.000000          5702.000000          5702.000000   
mean              0.561382             0.398281             0.006138   
std               0.496261             0.489587             0.078113   
min               0.000000             0.000000             0.000000   
25%               0.000000             0.000000             0.000000   
50%               1.000000             0.000000             0.000000   
75%               1.000000             1.000000             0.000000   
max               1.000000             1.000000             1.000000   

       income from wages_8  income from wages_9  
count          5702.000000          5702.000000  
mean              0.033497             0.000702  
std               0.179946             0.026479  
min               0.000000             0.000000  
25%               0.000000             0.000000  
50%               0.000000             0.000000  
75%               0.000000             0.000000  
max               1.000000             1.000000

In [25]:
# create the target
y = clean_df6['Taking diabetic pills_1.0']
y[:5]

0     1
1     1
8     0
12    1
15    0
Name: Taking diabetic pills_1.0, dtype: uint8

In [26]:
# check the balance of the target value
y.value_counts()

# result: good, 1:1 ratio of taking vs. not taking, no need to resample the data

0    2897
1    2805
Name: Taking diabetic pills_1.0, dtype: int64

### Split the data into train and test set

In [27]:
# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [28]:
# create a scaler instance
import sklearn as skl
X_scaler = skl.preprocessing.StandardScaler()

#from sklearn.preprocessing import StandardScaler

In [29]:
# fit/train the scaler
X_scaler.fit(X_train)

StandardScaler()

In [30]:
# scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [31]:
print (X_train_scaled)

[[-1.1262482   1.22617816 -0.0868335  -0.18600958 -0.02163205]
 [-1.1262482   1.22617816 -0.0868335  -0.18600958 -0.02163205]
 [-1.1262482   1.22617816 -0.0868335  -0.18600958 -0.02163205]
 ...
 [-1.1262482   1.22617816 -0.0868335  -0.18600958 -0.02163205]
 [-1.1262482   1.22617816 -0.0868335  -0.18600958 -0.02163205]
 [ 0.88790375 -0.81554217 -0.0868335  -0.18600958 -0.02163205]]


In [32]:
print(X_test_scaled)

[[ 0.88790375 -0.81554217 -0.0868335  -0.18600958 -0.02163205]
 [-1.1262482   1.22617816 -0.0868335  -0.18600958 -0.02163205]
 [ 0.88790375 -0.81554217 -0.0868335  -0.18600958 -0.02163205]
 ...
 [-1.1262482   1.22617816 -0.0868335  -0.18600958 -0.02163205]
 [ 0.88790375 -0.81554217 -0.0868335  -0.18600958 -0.02163205]
 [ 0.88790375 -0.81554217 -0.0868335  -0.18600958 -0.02163205]]


In [33]:
# 75% train, 25% test 
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(4276, 5)
(1426, 5)


In [34]:
# 75% train, 25% test 
print(y_train.shape)
print(y_test.shape)

(4276,)
(1426,)


In [35]:
# create a logistic regression model
model = LogisticRegression(solver='lbfgs', random_state=1)
model

#model.fit(X_scaled, y)

LogisticRegression(random_state=1)

In [36]:
# fit (train) model using the training data
model.fit(X_train_scaled, y_train)

LogisticRegression(random_state=1)

### make predictions

In [37]:
# # predict outcomes for the test data set
predictions = model.predict(X_test_scaled)
pd.DataFrame( {'Prediction': predictions, 'Acutal': y_test} )

Prediction  Acutal
28868           0       0
12947           1       1
3527            0       0
16349           0       0
5473            1       1
...           ...     ...
28848           1       0
15034           1       1
25553           1       0
21590           0       1
23840           0       0

[1426 rows x 2 columns]

In [38]:
# cal. the balanced accuracy score
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

# poor correlation between income and diabetes 

0.526889665010576

### graph of diabetic vs. income

In [39]:
clean_df4

Taking diabetic pills  income from wages
0                        1.0                  1
1                        1.0                  1
8                        2.0                  1
12                       1.0                  8
15                       2.0                  1
...                      ...                ...
29470                    1.0                  2
29473                    1.0                  2
29476                    1.0                  1
29478                    1.0                  1
29481                    1.0                  1

[5702 rows x 2 columns]

In [40]:
# try bar ? not useful 
y = clean_df4["Taking diabetic pills"]
x = clean_df4['income from wages']
plt.bar(x, y)

plt.title('income vs. diabetic')
plt.xlabel('income')
plt.ylabel('diabetic')

<IPython.core.display.Javascript object>

Text(0, 0.5, 'diabetic')

## looping over 38 cat. variables

In [41]:
s# define XY df and make a copy by .copy()
XY = clean_df2 [ [column, 'Taking diabetic pills'] ].copy()
XY

NameError: ignored

In [ ]:
# drop na by .dropna()
XY = XY.dropna()
XY

In [ ]:
# if : print
if len( XY > 0):
    print ("XY is greater than 0")

In [ ]:
# len(XY) > 0 always?
target_column = 'Taking diabetic pills'

for column in clean_df2.columns.values:
    if target_column != column:
        XY = clean_df2[ [column, 'Taking diabetic pills'] ].copy()
        XY = XY.dropna()
        if len( XY ) > 0:
            print ("XY > 0")

In [ ]:
# what is the length of XY df
len(XY)

In [ ]:
# There are 9 type of income from retirement?
XY.value_counts()

In [ ]:
X = pd.get_dummies( XY[ column ] )

In [ ]:
import sklearn as skl

target_column = "Taking diabetic pills"

target_column_onehot = '1.0'

for column in clean_df2.columns.values:
    if target_column != column:
        XY = clean_df2[ [column,"Taking diabetic pills"] ].copy()
        XY = XY.dropna()
        X = pd.get_dummies( XY[ column ].astype('str') )
        y = pd.get_dummies( XY[ target_column ].astype('str') ) 
        y = y[ target_column_onehot ]
        print(column,X.shape,y.shape)
        X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
        X_scaler = skl.preprocessing.StandardScaler()
        X_scaler.fit(X_train)
        X_train_scaled = X_scaler.transform(X_train)
        X_test_scaled = X_scaler.transform(X_test)
        model = LogisticRegression(solver='lbfgs', random_state=1)
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        print( column, "score", balanced_accuracy_score(y_test, y_pred) )
    #break

In [ ]:
import sklearn as skl

target_column = "Taking diabetic pills"

target_column_onehot = '1.0'

for column in clean_df2.columns.values:
    if target_column != column:
        XY = clean_df2[ [column,"Taking diabetic pills"] ].copy()
        XY = XY.dropna()
        if len( XY ) > 0:
            if len( XY[column] ) == len( XY[target_column] ):
                X = pd.get_dummies( XY[ column ].astype('str') )
                y = pd.get_dummies( XY[ target_column ].astype('str') ) 
                y = y[ target_column_onehot ]
                print(column,X.shape,y.shape)
                X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
                X_scaler = skl.preprocessing.StandardScaler()
                X_scaler.fit(X_train)
                X_train_scaled = X_scaler.transform(X_train)
                X_test_scaled = X_scaler.transform(X_test)
                model = LogisticRegression(solver='lbfgs', random_state=1)
                model.fit(X_train, y_train)
                y_pred = model.predict(X_test)
                print( column, "score", balanced_accuracy_score(y_test, y_pred) )
    #break

In [ ]:
clean_df2.columns

In [ ]:
import sklearn as skl

target_column = "Taking diabetic pills"
target_column_onehot = '1.0'

columns=['Age of sample adult',
         'Sex of sample adult',
         'Education of sample adult',
         'Single + Mult race gps w Hispanic origin',
         'income from wages']
XYcolumns = columns+[target_column]
print(XYcolumns)
XY = clean_df2.loc[ :, XYcolumns ].copy()
XY = XY.dropna()
X = pd.get_dummies( XY[ columns ].astype('str') )
y = pd.get_dummies( XY[ target_column ].astype('str') ) 
y = y[ target_column_onehot ]
print(columns,X.shape,y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
X_scaler = skl.preprocessing.StandardScaler()
X_scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print( "Score", balanced_accuracy_score(y_test, y_pred) )
    #break

In [ ]:
([1]+[2])

In [ ]:
# give column title loop thru the 38 col. 
#for column in clean_df2.columns.values:
     #  print(clean_df2.columns.values)

In [ ]:
for col in clean_df2:
    X = pd.get_dummies(clean_df2[col])
    print(X.head(5))

In [ ]:
for col in clean_df2.columns.values:
    X = pd.get_dummies(clean_df2[col])
    print(X.head(5))