# Linear regression 

In [1]:
#from sqlalchemy import create_engine
#import psycopg2
#from config import db_password

import pandas as pd
import numpy as np
from collections import Counter

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, confusion_matrix

In [2]:
# localserver, the connection string
#dbEngine = f"postgresql://postgres:{db_password}@127.0.0.1:5432/Drops_of_Jupyter"

# create the database engine
#engine = create_engine(dbEngine)
#conn = engine.connect()

In [3]:
# Read data from PostgreSQL database table and load into a DataFrame instance
#ghs_df = pd.read_sql("select * from general_health_status", conn);
#ghs_df

In [4]:
# Read data from PostgreSQL database table and load into a DataFrame instance
#ind_df = pd.read_sql("select * from individual", conn)
#ind_df

In [5]:
# merge two dfs
#clean_df2 = ghs_df.merge(ind_df, how='inner', on='ID')
#clean_df2

In [6]:
# columns in df
#clean_df2.columns

In [7]:
#clean_df2 = clean_df2.to_csv(r'/Users/yinglin/Desktop/NHIS/clean.csv')

In [8]:
clean_df2 = pd.read_csv('/Users/yinglin/Desktop/NHIS/clean.csv')
clean_df2 

Unnamed: 0       ID General_Health_Status Diabetes Prediabetes  \
0               0  H056808             Very_Good       no         yes   
1               1  H018779             Very_Good      yes         yes   
2               2  H049265             Very_Good       no          no   
3               3  H007699                  Fair       no          no   
4               4  H066034                  Good       no          no   
...           ...      ...                   ...      ...         ...   
29477       29477  H012375             Very_Good       no          no   
29478       29478  H052160                  Fair      yes         yes   
29479       29479  H051563             Very_Good       no          no   
29480       29480  H058432                  Good       no          no   
29481       29481  H052354                  Fair      yes         yes   

       Weight_Lbs Categorical_BMI Region  Age  Gender  \
0           199.0      Overweight  South   50    Male   
1           205.0      Overweight  South   53    Male   
2           160.0      Overweight  South   56    Male   
3           190.0           Obese  South   57  Female   
4           250.0           Obese  South   25    Male   
...           ...             ...    ...  ...     ...   
29477       140.0      Overweight   West   70  Female   
29478       220.0           Obese   West   35  Female   
29479       130.0      Overweight   West   72  Female   
29480       168.0  Healthy_Weight   West   58    Male   
29481       184.0           Obese   West   57  Female   

                         Education                   Race  Poverty_Ratio  
0                       Grade_1-11             White_Only           1.93  
1      Associates_Academic_Program  African_American_Only           4.45  
2                         Bachelor             White_Only           5.94  
3           Some_College_no_degree             White_Only           3.70  
4             High_School_Graduate  African_American_Only           1.66  
...                            ...                    ...            ...  
29477                      Masters             White_Only           5.11  
29478  Associates_Academic_Program        Not_Ascertained           3.03  
29479         High_School_Graduate             White_Only           2.07  
29480       Some_College_no_degree             White_Only           2.05  
29481         High_School_Graduate             White_Only           4.89  

[29482 rows x 13 columns]

In [9]:
import sklearn as skl
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

target_column = "Diabetes"
target_column_onehot = 'yes'

columns=[
        'Categorical_BMI',
         'Education',
         'Poverty_Ratio'
         ]
         
columnsCAT=[
         'Categorical_BMI',
         'Education',
         ]

XYcolumns = columns+[target_column]
print(XYcolumns)
XY = clean_df2.loc[ :, XYcolumns ].copy()
XY = XY.dropna()
#X = pd.get_dummies( XY[ columnsCAT ].astype('str') )
#X = pd.get_dummies( XY[ columns ].astype('str'), columns=columnsCAT )
X = pd.get_dummies( XY[ columns ], columns=columnsCAT )
#X = XY[ columns ]
y_ = pd.get_dummies( XY[ target_column ].astype('str') ) 
y = y_[ target_column_onehot ]
print(columns,X.shape,y.shape)
print(XY.head() )
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
X_scaler = skl.preprocessing.StandardScaler()
X_scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# implement random oversampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_resampled, y_resampled)

# Make predictions using the testing set
y_pred = regr.predict(X_test_scaled)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))

    #break

['Categorical_BMI', 'Education', 'Poverty_Ratio', 'Diabetes']
['Categorical_BMI', 'Education', 'Poverty_Ratio'] (29482, 18) (29482,)
  Categorical_BMI                    Education  Poverty_Ratio Diabetes
0      Overweight                   Grade_1-11           1.93       no
1      Overweight  Associates_Academic_Program           4.45      yes
2      Overweight                     Bachelor           5.94       no
3           Obese       Some_College_no_degree           3.70       no
4           Obese         High_School_Graduate           1.66       no
Coefficients: 
 [-4.91660323e-02  8.71782906e+10  8.71471369e+10  8.88536190e+10
  2.39464607e+10  2.92834106e+10 -1.25323197e+11 -2.83336558e+11
 -1.89917439e+11 -4.24216789e+11 -5.94110775e+10 -1.45548813e+11
 -2.50160627e+11 -1.93692701e+11 -4.14632051e+11 -3.15756251e+11
 -4.23124256e+10 -3.53514835e+11]
Mean squared error: 0.23
Coefficient of determination: -1.43


In [10]:
XY['Categorical_BMI'].value_counts()

Overweight        9917
Obese             9225
Healthy_Weight    9144
Unknown            733
Underweight        463
Name: Categorical_BMI, dtype: int64

In [11]:
np.unique(y_pred, return_counts=True )

(array([0.0162735 , 0.02066803, 0.03958893, ..., 0.82633209, 0.82645416,
        0.83646393]),
 array([1, 5, 1, ..., 1, 1, 1]))

In [12]:
np.unique(y_test, return_counts=True )

(array([0, 1], dtype=uint8), array([6587,  784]))

In [13]:
y.value_counts()

0    26348
1     3134
Name: yes, dtype: int64

In [14]:
clean_df2['Poverty_Ratio']

0        1.93
1        4.45
2        5.94
3        3.70
4        1.66
         ... 
29477    5.11
29478    3.03
29479    2.07
29480    2.05
29481    4.89
Name: Poverty_Ratio, Length: 29482, dtype: float64

In [15]:
y_['yes'].value_counts()

0    26348
1     3134
Name: yes, dtype: int64

In [16]:
X_train_scaled.shape

(22111, 18)

In [17]:
X_test_scaled.shape

(7371, 18)